import { existsSync } from "node:fs";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import openapiTS, { astToString } from "openapi-typescript";
import {
  ARTIFACT_PATH,
  CACHED_SPEC_PATH,
  FETCH_MANIFEST_PATH,
  GENERATOR_NAME,
  MANIFEST_PATH,
  fail,
  installedGeneratorVersion,
  readJson,
  sha256,
  writeJson,
} from "./lib.mjs";

// Alphabetized output keeps spec-upgrade diffs about semantics rather than
// Apple's entry ordering. Recorded in the manifest so a regeneration is
// reproducible from the manifest alone.
const GENERATOR_OPTIONS = { alphabetize: true };

if (!existsSync(CACHED_SPEC_PATH) || !existsSync(FETCH_MANIFEST_PATH)) {
  fail(
    `No cached spec at ${CACHED_SPEC_PATH}. Run \`npm run contract:fetch\` first (or \`npm run contract:update\` for the full pipeline).`,
  );
}
const specBytes = await readFile(CACHED_SPEC_PATH);
const fetchManifest = await readJson(FETCH_MANIFEST_PATH);
const specSha256 = sha256(specBytes);
if (specSha256 !== fetchManifest.sha256) {
  fail(
    `Cached spec does not match its fetch record; the cache is corrupt. Re-run \`npm run contract:fetch\`.`,
  );
}

const spec = JSON.parse(specBytes.toString("utf8"));
const generatorVersion = installedGeneratorVersion();

console.log(
  `Generating contract from ${spec.info.title} ${spec.info.version} with ${GENERATOR_NAME} ${generatorVersion}…`,
);
const ast = await openapiTS(spec, GENERATOR_OPTIONS);

// The banner carries only content-derived facts (no timestamps): identical
// inputs must yield byte-identical output on every platform and every run.
const banner = `/**
 * Generated by ${GENERATOR_NAME} ${generatorVersion}.
 * Source: ${spec.info.title} spec ${spec.info.version} (sha256 ${specSha256}).
 * DO NOT EDIT. Regenerate with \`npm run contract:update\`.
 */

`;
const artifact = (banner + astToString(ast)).replace(/\r\n/g, "\n");
const artifactBytes = Buffer.from(artifact, "utf8");

// A re-run on an unchanged spec must be a zero-diff no-op, so the capture
// time survives from the committed manifest rather than the fresh fetch.
let fetchedAt = fetchManifest.fetchedAt;
if (existsSync(MANIFEST_PATH)) {
  const previous = await readJson(MANIFEST_PATH);
  if (previous.spec?.sha256 === specSha256 && previous.spec.fetchedAt) {
    fetchedAt = previous.spec.fetchedAt;
  }
}

await mkdir(path.dirname(ARTIFACT_PATH), { recursive: true });
await writeFile(ARTIFACT_PATH, artifactBytes);
await writeJson(MANIFEST_PATH, {
  manifestVersion: 1,
  spec: {
    title: spec.info.title,
    version: spec.info.version,
    openapiVersion: spec.openapi,
    sourceUrl: fetchManifest.sourceUrl,
    fetchedAt,
    sha256: specSha256,
  },
  generator: {
    name: GENERATOR_NAME,
    version: generatorVersion,
    options: GENERATOR_OPTIONS,
  },
  output: {
    file: ARTIFACT_PATH,
    sha256: sha256(artifactBytes),
  },
});

const lineCount = artifact.split("\n").length;
console.log(
  `Wrote ${ARTIFACT_PATH} (${String(artifactBytes.length)} bytes, ${String(lineCount)} lines) and ${MANIFEST_PATH}`,
);
